// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChT8UY0MhedQtrRM_JrjN2LvbKNM6yzGg',
    appId: '1:178216866789:web:0eacfb40c32a3bf2d8550c',
    messagingSenderId: '178216866789',
    projectId: 'hovee-558db',
    authDomain: 'hovee-558db.firebaseapp.com',
    storageBucket: 'hovee-558db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS7a8hQ_y_gAkNm7NfylEdyriREN677js',
    appId: '1:178216866789:android:c47e204c5d5de599d8550c',
    messagingSenderId: '178216866789',
    projectId: 'hovee-558db',
    storageBucket: 'hovee-558db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ZnFgMYCC3uFctvd7wSL_zkXtkImdtNI',
    appId: '1:178216866789:ios:acdbca2101dbfc44d8550c',
    messagingSenderId: '178216866789',
    projectId: 'hovee-558db',
    storageBucket: 'hovee-558db.firebasestorage.app',
    androidClientId: '178216866789-d8f78unbmfguq8q4rv870607t929ki9u.apps.googleusercontent.com',
    iosClientId: '178216866789-gpuvp8c97q9007v1rrcurfrs09pdb9pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoveeRentChatPocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ZnFgMYCC3uFctvd7wSL_zkXtkImdtNI',
    appId: '1:178216866789:ios:acdbca2101dbfc44d8550c',
    messagingSenderId: '178216866789',
    projectId: 'hovee-558db',
    storageBucket: 'hovee-558db.firebasestorage.app',
    androidClientId: '178216866789-d8f78unbmfguq8q4rv870607t929ki9u.apps.googleusercontent.com',
    iosClientId: '178216866789-gpuvp8c97q9007v1rrcurfrs09pdb9pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hoveeRentChatPocApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChT8UY0MhedQtrRM_JrjN2LvbKNM6yzGg',
    appId: '1:178216866789:web:2fa7b9a89d40f48ed8550c',
    messagingSenderId: '178216866789',
    projectId: 'hovee-558db',
    authDomain: 'hovee-558db.firebaseapp.com',
    storageBucket: 'hovee-558db.firebasestorage.app',
  );
}
